version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-app
    image: parkbee-app:latest
    environment:
      API_HOST: api
      API_PORT: 3000
      HTTP_PORT: 80
      MONGODB_CONNECTION_STRING: mongodb://admin:admin@mongodb:27017
    ports:
      - "3333:80"
    depends_on:
      - mongodb

  api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-api
    image: parkbee-api:latest
    environment:
      MONGODB_USER: igor.mardari
      MONGODB_PASSWORD: TU=M9t;lGj#Qr1k
      HTTP_PORT: 80
    ports:
      - "3000:80"
    depends_on:
      - mongodb
