version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-app
    environment:
      API_HOST: api
      API_PORT: 3000
      HTTP_PORT: 80
    ports:
      - "3333:80"

  api:
    build:
      context: ./docker/src/api
      dockerfile: ./Dockerfile
    environment:
      # Below are no longer use since executable ./docker/src/api is having the hardcoded MONGO_HOST and it cannot be used
      # MONGODB_USER: devops
      # MONGODB_PASSWORD: pICBMdNaNmG7Ebra
      HTTP_PORT: 3000
    ports:
      - "3000:3000"
