version: '3'

services:
  app:
    build:
      context: ./docker/src/app
      dockerfile: ./Dockerfile
    environment:
      API_HOST: api
      API_PORT: 3000
      HTTP_PORT: 80
    ports:
      - "3000:80"

  api:
    build:
      context: ./docker/src/api
      dockerfile: ./Dockerfile
    environment:
      # Below vars are no longer used since executable ./docker/src/api-executable is having the hardcoded MONGO_HOST and it cannot be used
      # MONGODB_USER: devops
      # MONGODB_PASSWORD: pICBMdNaNmG7Ebra
      HTTP_PORT: 4000
    ports:
      - "4000:4000"
