version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-app
    environment:
      API_HOST: api
      API_PORT: 3000
      HTTP_PORT: 80
    ports:
      - "3333:80"

  api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-api
    environment:
      MONGODB_USER: devops
      MONGODB_PASSWORD: z6K1v5j6G5zan2c7
      HTTP_PORT: 80
    ports:
      - "3000:80"
