apiVersion: v1
kind: Config
preferences: {}

clusters:
- name: parkbee-cluster
  cluster:
    server: https://11B653DE92D767972CF0BF1C49762847.sk1.eu-north-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUzJLRGFjLzN3RWd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeU1ESXdNVE0wTlROYUZ3MHpOREF4TXpBd01UTTVOVE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBUlZuVm5RSXpsZFBCNGFaSlliaGsvRE1CV3h0T2p2alBzWEM5K1hkYTM1QkNaS0c0TmFpZS9WQ1QKU2NENHZrbUx0WnFlMlNYUXJ3TXI5aks1VVhTNlpJZnNrVkVySmtBYUtLdzljNkFrSmlaZ2h4bzdWaCtkUVg0SAprT1dzdWJjSFFKMkpKWG9wcGFnV1RXNVdnc2dRRWM3eStURlR5MWxIOTl2MVRLeStnVjJHRlQ3aUtaYXluRzV6CktORG1Wa25LMVdYNnVGWlVSVzlNL3IvUnJxQmgxZERkblloLzVjVkFYS29sdWhHd3BxVVBrckQ1SjZacWlvMWEKc2dGVnZMSm1GYVUvV3FIWWhQZGw1cmFxZ2ZQa2FBSFMyY3FiUW5scDZWTXUzeEVIMEg2ZjNwQThXczZVVzIzZgpyNlg3b1hKYWFpb1JObzBDZ3pFSXFneEdBcmFuQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRUEttOWxwOEFzOXR5L1BSa2NPUmhlU2hGZWN6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWI5NDJxUm1IYQpzSTBTWTA2Vk1nemJrQWV6RTJRSG0wbVFFZUVLTW5ZZ1h1bFV1V2h0UXRudmdldWkrOWlmSCt5SkNPbDQvTzh0CkE1MjlPTDdKTyt5MFEwVy9BamZ4a3BtR3dxRjN4bkFRaitGYzhsZGpLWWl3UzVRQU1nMmRrVHpDYWxnbE1RT28KcTNaT3ZtbXZ3SWt1VExvM2N0Q29JakpvRDAzdkJ5ZGo3Vi80V2kwem01czlVRlZIa3dJZnlZVkZwc0Vkci9wRQoxd3JUd2VXZ2t3c1J5NUkxVk9OdnFzR2FBcFJnV1J1WFhWb2hUaWVSR1FleTBMeVBNTEJ6OHBCZThDRXFFZDZqCmZ2eXloeG9FVEpyR2N0Y04wSVB3a0RsNm1kZlRndDNvZkZJT05OV00vaXVuNFppVnIwWkpqM2RJa0xubmhnWGoKUTczT0VCajV6Y3BYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

users:
- name: limited-access-user
  user:
    # A kube admin should run this command in order to get the token:
    # kubectl get secret limited-access-account-token -n myapp -o jsonpath='{.data.token}' | base64 --decode
    token: <YOUR_TOKEN>

contexts:
- name: limited-access-context
  context:
    cluster: parkbee-cluster
    user: limited-access-user
    namespace: myapp

current-context: limited-access-context



# export KUBECONFIG=/path/to/limited-access-kubeconfig.yaml