apiVersion: v1
kind: Secret
metadata:
  name: apps-secrets
type: Opaque
data:
  MONGODB_USER: eW91cl9tb25nb2RiX3VzZXI= #your_mongodb_user
  MONGODB_PASSWORD: eW91cl9tb25nb2RiX3Bhc3N3b3Jk #your_mongodb_password