apiVersion: v1
kind: ServiceAccount
metadata:
  name: limited-access-account
  namespace: myapp

---
apiVersion: v1
kind: Secret
metadata:
  name: limited-access-account-token
  namespace: myapp
  annotations:
    kubernetes.io/service-account.name: limited-access-account
type: kubernetes.io/service-account-token


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: myapp
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: myapp
subjects:
- kind: ServiceAccount
  name: limited-access-account
  namespace: myapp
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io